export const artists = [
  {
    id: "ksivat",
    name: "Ksivat",
    photo: "https://i.postimg.cc/j2v0Q6bv/IMG-20260514-235230.jpg",
    banner:
      "https://i.postimg.cc/JzjhqSHB/IMG-20260531-030824.png",
  },
  {
    id: "dollova",
    name: "Dollova",
    photo: "https://i.postimg.cc/Dy1Fqykg/IMG-6491.jpg",
    banner: "https://i.postimg.cc/mktPbr3s/IMG-6757.png",
  },
  {
    id: "sicka",
    name: "SiCka",
    photo:
      "https://i.postimg.cc/8CftN5QF/file-00000000ee1c7243a3b826e3a21ef389.png",
    banner:
      "https://i.postimg.cc/ZKKYKdVY/file-00000000174471f494946ff02adc6dd1.png",
  },
  {
    id: "various-artists",
    name: "Various Artists",
    photo: "https://i.postimg.cc/brkbcBDW/IMG-20260428-110522-876.jpg",
  },
  {
    id: "avya-asti",
    name: "АВЯ ASTI",
    photo: "https://i.postimg.cc/4dn98FKs/IMG-20260508-153413-715.jpg",
    banner: "https://i.postimg.cc/FF7GpqCY/IMG-7437.jpg",
  },
  {
    id: "pavlova-cookie",
    name: "Pavlova Cookie",
    photo: "https://i.postimg.cc/pyM5LWqw/IMG-20260508-153358-589.jpg",
    banner: "https://i.postimg.cc/WzChtPS9/IMG-20260524-015124-491.jpg",
  },
  {
    id: "niksa",
    name: "NIK$A",
    photo: "https://i.postimg.cc/pLtK2ZSs/IMG-20260508-153516.jpg",
  },
  {
    id: "ariana-grande",
    name: "Ariana Grande",
    photo: "https://i.postimg.cc/mk2WmBGq/IMG-20260516-160421-081.jpg",
    banner: "https://i.postimg.cc/7hWVzDkB/IMG-20260524-190314-323.jpg",
    isGlobal: true,
  },
];

export const reviews = [
  {
    id: "dollova-melon18-single",
    artistId: "dollova",
    isSingle: true,
    title: "MELON 18+",
    cover: "https://i.postimg.cc/xjHN6tkM/IMG-6891.jpg",
    releaseDate: "2026-05-22",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "DirtyDollyRecords",
    text: "Достаточно сексуальный несексуальный, по первой задумке, сингл с третьего альбома рэперки. Да, это явный эталон качества не только Долловой, но и всей хуендустрии. Обложка идеально подходит для рекламы OnlyFans / Fansly.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 9 }
    ]
  },
  {
    id: "dollova-madam-cum-single",
    artistId: "dollova",
    isSingle: true,
    title: "Madam Cum",
    cover: "https://i.postimg.cc/13whF9J1/IMG-20260508-141150-015.jpg",
    releaseDate: "2025-10-31",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "DirtyDollyRecords",
    text: "Игривооскорбляющая подача даёт одновременно и «какого хуя», и «ммм».",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "dollova-ugly-doll-single",
    artistId: "dollova",
    isSingle: true,
    title: "Ugly Doll",
    cover: "https://i.postimg.cc/x1CQp2xf/IMG-20260507-201146-613.jpg",
    releaseDate: "2026-01-30",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "DirtyDollyRecords",
    text: "Немного по-хайпер-попски, что для артистки немного в новинку, но она все равно справляется с этим.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "dollova-bot-hitches-single",
    artistId: "dollova",
    isSingle: true,
    title: "Bot Hitches",
    cover: "https://i.postimg.cc/3RMZvTSL/IMG-20260508-141204-583.jpg",
    releaseDate: "2025-11-14",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "DirtyDollyRecords",
    text: "Тётка разбушевалась и голос кажется, как из видео «быстро убрала телефон и собрала игрушки».",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "dollova-livaj-single",
    artistId: "dollova",
    isSingle: true,
    title: "ливай",
    cover: "https://i.postimg.cc/C5Nhzysz/IMG-20260507-230858-435.jpg",
    releaseDate: "2025-07-25",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "DirtyDollyRecords",
    text: "Мелодичный поп-рэп-трек, который можно было назвать РнБ, но я не буду.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "sicka-shut-that-hole-up-single",
    artistId: "sicka",
    isSingle: true,
    title: "Shut That Hole Up",
    cover: "https://i.postimg.cc/9QXsNGBb/file-00000000e770720a97fcb5b159765252.png",
    releaseDate: "2026-04-26",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Farting Lesbians",
    text: "Даёт по ебалу и затыкает не рот, а жопу.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "sicka-perdanovna-single",
    artistId: "sicka",
    isSingle: true,
    title: "Пердановна",
    cover: "https://i.postimg.cc/dtfNV89z/IMG-20260508-140543-332.jpg",
    releaseDate: "2025-10-29",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / SiCka",
    text: "Заедающее отчество — что-то новое и слава богу.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "sicka-smack-it-up-single",
    artistId: "sicka",
    isSingle: true,
    title: "Smack It Up",
    cover: "https://i.postimg.cc/X7TX3Yp1/IMG-20260508-141934-156.jpg",
    releaseDate: "2025-11-16",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Farting Lesbians",
    text: "Танцевальный cunty трек, который предлагает заставить слушателя заставить артистку рыгать.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "sicka-slayyyter-fspr-single",
    artistId: "sicka",
    artistIds: ["sicka"],
    isSingle: true,
    title: "FSPR (feat. Slayyyter)",
    cover: "https://i.postimg.cc/k4sdqQyY/IMG-20260507-224212-538.jpg",
    releaseDate: "2025-07-13",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / SiCka",
    text: "Воссоединение двух артисток, которых различить можно, только если послушать первую версию трека.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "sicka-dermishche-single",
    artistId: "sicka",
    isSingle: true,
    title: "Дерьмище",
    cover: "https://i.postimg.cc/zBDVMH43/IMG-20260508-135900-151.jpg",
    releaseDate: "2025-09-21",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / SiCka",
    text: "Молитва, канон и все что угодно в одном лице. Вам нужно это услышать и выучить наизусть, иначе я не знаю, зачем вы существуете вообще в хуендустрии.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "sicka-im-ready-single",
    artistId: "sicka",
    isSingle: true,
    title: "I'M READY",
    cover: "https://i.postimg.cc/gk8ytgkc/IMG-20260507-230349-727.jpg",
    releaseDate: "2025-07-22",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / SiCka",
    text: "Трек из неудавшегося микстейпа. Из синглов было настолько нечего выбрать на этом релизе, что... Что?",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 }
    ]
  },
  {
    id: "sicka-suck-tomorrow-single",
    artistId: "sicka",
    isSingle: true,
    title: "SUCK TOMORROW",
    cover: "https://i.postimg.cc/MTVJ7zWn/IMG-20260508-142142-723.jpg",
    releaseDate: "2025-12-01",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Farting Lesbians",
    text: "Artist promoted this track everywhere, but no one heard it. The extremely narrow genre in the industry makes this track unnoticed. But in vain.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 7 }
    ]
  },
  {
    id: "sicka-and-my-pussy-ah-single",
    artistId: "sicka",
    isSingle: true,
    title: "And My Pussy-ah",
    cover: "https://i.postimg.cc/KzMgWYrZ/IMG-20260507-223723-016.jpg",
    releaseDate: "2025-06-26",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / SiCka",
    text: "Данный трек нужно слушать в первую очередь, если хотите ознакомиться с творчеством SiCka.",
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "sicka-cksu-single",
    artistId: "sicka",
    isSingle: true,
    title: "CkSu",
    cover: "https://i.postimg.cc/dVLjJJJj/IMG-20260507-221846-478.jpg",
    releaseDate: "2025-05-17",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / SiCka",
    text: "Мне нечего сказать.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "avya-asti-baby-single",
    artistId: "avya-asti",
    isSingle: true,
    title: "BABY",
    cover: "https://i.postimg.cc/YC8b4ZYY/IMG-20260508-151118-057.jpg",
    releaseDate: "2026-03-21",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "OOO LABLE MALIK DELGATY AND AVEE ASTI",
    text: "Очень коммерческий трек, который вызывает драйв своим припевом и даёт либидо.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "avya-asti-strap-on-single",
    artistId: "avya-asti",
    isSingle: true,
    title: "STRAP ON",
    cover: "https://i.postimg.cc/Kz23rvPb/IMG-20260508-144517-057.jpg",
    releaseDate: "2026-01-23",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / АВЯ ASTI",
    text: "Для секса в душе.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "avya-asti-bdsm-single",
    artistId: "avya-asti",
    isSingle: true,
    title: "BDSM",
    cover: "https://i.postimg.cc/1X0snxPn/IMG-20260507-222633-360.jpg",
    releaseDate: "2025-06-20",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Independent / АВЯ ASTI",
    text: "Ну.",
    singleCriteria: [
      { title: "Куплеты", score: 7 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 }
    ]
  },
  {
    id: "niksa-puffmeedy-single",
    artistId: "niksa",
    isSingle: true,
    title: "PuffMeedy",
    cover: "https://i.postimg.cc/1zcjx9mQ/IMG-20260507-231349-872.jpg",
    releaseDate: "2025-07-26",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Yandex Market Records",
    text: "Дисс-трек, который предназначен в сторону креветятины. Забавно наблюдать за тем, как они сейчас лучшие подруги.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 }
    ]
  },
  {
    id: "pavlova-cookie-govno-na-ventiljator-single",
    artistId: "pavlova-cookie",
    isSingle: true,
    title: "ГОВНО НА ВЕНТИЛЯТОР",
    cover: "https://i.postimg.cc/nhHJCwXF/IMG-20260507-232554-471.jpg",
    releaseDate: "2025-08-22",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Yandex Market Records",
    text: "Немного дисс, немного говно, и я про название, а не про то, что трек плохого качества.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 }
    ]
  },
  {
    id: "pavlova-cookie-skinny-jeanz-single",
    artistId: "pavlova-cookie",
    isSingle: true,
    title: "skinny jeanz",
    cover: "https://i.postimg.cc/FRHjfRpB/IMG-20260508-213011-967.jpg",
    releaseDate: "2026-05-09",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "YMR & Farting Lesbians",
    text: "Ранее входивший во второй альбом артистки сингл вошёл в мою жопу.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 }
    ]
  },
  {
    id: "pavlova-cookie-vne-ocheredi-single",
    artistId: "pavlova-cookie",
    isSingle: true,
    title: "ВНЕ ОЧЕРЕДИ",
    cover: "https://i.postimg.cc/Y2JwkCNB/IMG-20260507-224606-965.jpg",
    releaseDate: "2025-06-28",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Yandex Market Records",
    text: "Артистка умоляет, чтобы ей было хорошо.",
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 }
    ]
  },
  {
    id: "ariana-grande-we-cant-be-friends-single",
    artistId: "ariana-grande",
    isSingle: true,
    title: "we can't be friends (wait for your love)",
    cover: "https://i.postimg.cc/0NLmTyZj/IMG-20260527-225945-177.jpg",
    releaseDate: "2024-07-19",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Republic Records",
    text: "Очень нежный и холодный одновременно трек — будто танцуешь и грустишь в один момент. Синты и вокал создают ощущение красивого эмоционального отдаления, которое долго не отпускает.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 9 }
    ]
  },
  {
    id: "ariana-grande-hate-that-i-made-you-love-me-single",
    artistId: "ariana-grande",
    isSingle: true,
    title: "hate that i made you love me",
    cover: "https://images.genius.com/460168ceb0f9e0c6637bd802d65aaf43.1000x1000x1.png",
    releaseDate: "2026-05-29",
    reviewDate: "2026-05-29T00:00:00Z",
    label: "Babydoll Music",
    text: "Новый сингл поп-артистки звучит нежно, холодно и очень лично. Ариана будто шепчет сожаление прямо в ухо, а минималистичный продакшн только усиливает это чувство. Трек открывает эру грядущего восьмого альбома «petal» по-музыкальному и является лид-синглом к нему.",
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 }
    ]
  },
  {
    id: "ariana-grande-twilight-zone-single",
    artistId: "ariana-grande",
    isSingle: true,
    title: "twilight zone",
    cover: "https://i.postimg.cc/k5tRvd9F/IMG-20260527-230032-827.jpg",
    releaseDate: "2025-06-20",
    reviewDate: "2026-05-27T00:00:00Z",
    label: "Republic Records",
    text: "Ариана звучит так, будто она пытается понять, была ли прошлая любовь вообще реальной или это был странный сон. Трек очень воздушный и меланхоличный — у него вайб ночной поездки по пустому городу после эмоционального выгорания.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 10 }
    ]
  },
  {
    id: "various-artists-huevision-2026-ep",
    artistId: "various-artists",
    title: "Huevision 2026 — The Official Album EP",
    cover: "https://i.postimg.cc/htM2dHcr/file-00000000b90c7246b04a6c0cd0d4d2aa.png",
    releaseDate: "2026-06-13",
    label: "HUEVKI",
    text: "Неизвестно",
    isUpcoming: true,
    tracks: [
      { title: "Dollova \u2014 BIKINI" },
      { title: "Pavlova Cookie \u2014 \u0434\u0430\u044f\u0438\u0437\u0432\u043e\u0440\u043e\u043d\u0435\u0436\u0430" },
      { title: "SiCka \u2014 Rev\u014d" },
      { title: "Ksivat \u2014 Song #1" },
    ],
    criteria: [
      { title: "Биты" },
      { title: "Флоу" },
      { title: "Потенциал хита" },
      { title: "Визуал" },
    ],
  },
  {
    id: "sicka-kfc-freestyle-single",
    artistId: "sicka",
    isSingle: true,
    title: "KFC Freestyle",
    cover: "https://i.postimg.cc/SQMwhNWg/file-00000000be487243b2b54a0512a105cd.png",
    releaseDate: "2026-05-24",
    reviewDate: "2026-05-24T00:00:00Z",
    label: "Farting Lesbians",
    text: "Перед нами классический пример репрезент-трека, который пытается выехать на гиперболизированном эпатаже и грязном юморе, но спотыкается о техническую реализацию. Работа звучит как мем-рэп первой волны, где забавная концепция разбивается о сырое сведение и ленивый перформанс.",
    singleCriteria: [
      { title: "Куплеты", score: 4 },
      { title: "Припев", score: 5 },
      { title: "Дополнительно", score: 3 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 4 },
      { title: "Потенциал хита", score: 3 },
      { title: "Визуал", score: 9 }
    ]
  },
  {
    id: "sicka-united-states-of-sicka",
    artistId: "sicka",
    title: "United States Of SiCka",
    cover:
      "https://i.postimg.cc/yddB6XY8/file-0000000083a47246a1087a141da0ebe2.png",
    releaseDate: "2026-07-24",
    label: "Farting Lesbians",
    text: "Неизвестно",
    isUpcoming: true,
    criteria: [
      { title: "Биты" },
      { title: "Флоу" },
      { title: "Потенциал хита" },
      { title: "Визуал" },
    ],
  },
  {
    id: "ksivat-no-stress",
    artistId: "ksivat",
    isSingle: true,
    title: "No Stress",
    cover: "https://i.postimg.cc/Rh6Y5jFf/IMG-20260524-023529-771.jpg",
    releaseDate: "2026-02-13",
    reviewDate: "2026-05-24T00:00:00Z",
    label: "DPM Records",
    text: "Хорошенький фристайл по мотивам трека Госпожи Эвелин — «Антилопа». Тут артистка хвалится своими «достижениями» и выпендрежом, ну, в целом, как обычно.",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "dollova-uvolen",
    artistId: "dollova",
    title: "УВОЛЕН",
    cover: "https://i.postimg.cc/t4CPkbDL/IMG-20260518-151848-021.jpg",
    releaseDate: "2025-07-13",
    reviewDate: "2026-05-18T12:07:00Z",
    label: "DirtyDollyRecords",
    text: "Артистка, в связи с увольнением со своей работы не по своей воле, представляет новый трек. В этом диссе рэперка показывает не грусть того, что она была уволена, а наоборот, радость, ведь начальник ещё та уродливая сучка, и как он смеет пиздеть на саму Доллову?",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "sicka-go-sicka-go-single",
    artistId: "sicka",
    title: "Go! SiCka! Go!",
    cover: "https://i.postimg.cc/4NYYJ96C/IMG-20260517-002108-458.jpg",
    releaseDate: "2026-01-02",
    reviewDate: "2026-05-17T12:00:00Z",
    label: "Farting Lesbians",
    text: "Выебывающий vogue бит и заедающий ритм делают свое дело. Этот трек есть эталон всех drag шоу в будущем.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "avya-asti-slap-slap-single",
    artistId: "avya-asti",
    title: "SLAP, SLAP",
    cover: "https://i.postimg.cc/8C9y0Wm5/IMG-20260517-001026-346.jpg",
    releaseDate: "2026-05-17",
    reviewDate: "2026-05-17T12:00:00Z",
    label: "OOO LABLE MALIK DELGATY AND AVEE ASTI",
    text: "Агрессивный рэп-трек, который заставляет хлопать своей попенькой. Артистка немного поигралась со сведением, из-за чего она звучит, как в клетке, но это все равно не мешает нам удовлетворить свои потребности под данное произведение.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "sicka-jesos-single",
    artistId: "sicka",
    title: "JeSOS",
    cover: "https://i.postimg.cc/ZqKtLJFn/IMG-20260516-153638-544.jpg",
    releaseDate: "2026-02-17",
    reviewDate: "2026-05-16T13:30:00Z",
    label: "Farting Lesbians",
    text: "Сингл с третьего альбома рэперки, который нацелен на заедание в голове своим многоструктурным припевом, с чем он так-то вот так-то справляется. Тема об Иисусе и том, что она есть Иисус, и то, что она вообще выбрала это синглом, добавляет провокационных красок в карьеру артистки.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "ksivat-mommy-single",
    artistId: "ksivat",
    title: "Mommy",
    cover: "https://i.postimg.cc/sDgsfDSJ/IMG-20260516-153610-878.jpg",
    releaseDate: "2025-12-09",
    reviewDate: "2026-05-16T13:00:00Z",
    label: "DPM Records",
    text: "Очередной трек от артистки под продюсированием нишевой долбоебки. Трек имеет заедающий припев и хороший бит.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "ugly-doll",
    artistId: "dollova",
    title: "Ugly Doll EP",
    cover: "https://i.postimg.cc/x1CQp2xf/IMG-20260507-201146-613.jpg",
    releaseDate: "2026-01-30",
    reviewDate: "2026-02-21",
    label: "DirtyDollyRecords",
    text: "Артистка доказывает, что умеет звучать хорошо во всех звуках и жанрах, но даже так может продолжить работать в одном и том же. Не смотря на это, качество мини-альбома все равно перебивает этот недостаток.",
    tracks: [
      { title: "Girlss", score: 9 },
      { title: "Priority", score: 6 },
      { title: "Ugly Doll", score: 10 },
      { title: "Booty Drop", score: 9, singleId: "dollova-sicka-booty-drop-single" },
      { title: "Fat Classic", score: 8 },
      { title: "Shopping", score: 8 },
      { title: "Fat Guest 2", score: 8 },
      { title: "BuBuBu", score: 9 },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "ahh",
    artistId: "sicka",
    title: "ahh... EP",
    cover: "https://i.postimg.cc/dVLjJJJj/IMG-20260507-221846-478.jpg",
    releaseDate: "2025-05-17",
    reviewDate: "2025-07-08",
    label: "Independent / SiCka",
    text: "Пердеть в туалете и на члене одновременно, при этом играя в кукиран — это только ее стихия.",
    tracks: [
      { title: "Не пернешь", score: 7 },
      { title: "CkSu", score: 9 },
      { title: "LGBTшки", score: 7 },
      { title: "No Cookies", score: 7 },
      { title: "Okurr", score: 6 },
      { title: "Gay&Mono", score: 4 },
      { title: "Touch It", score: 7 },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "huevision-2025",
    artistId: "various-artists",
    title: "Huevision 2025 — Album EP",
    cover: "https://i.postimg.cc/brkbcBDW/IMG-20260428-110522-876.jpg",
    releaseDate: "2025-06-08",
    reviewDate: "2026-05-18T12:06:00Z",
    reviewDateDisplay: "08.07.2025 / 18.05.2026 (новая)",
    label: "HUEVKI",
    text: "Самое разностороннее шоу из когда-либо бывавших в узком телеграме с замечательными композициями",
    tracks: [
      { title: "SiCka — Let Me", score: 9, singleId: "sicka-let-me-single" },
      {
        title: "NIK$A — Business",
        score: 9,
        singleId: "niksa-business-single",
      },
      {
        title: "Ksivat — 5 Minutes",
        score: 10,
        singleId: "ksivat-5-minutes-single",
      },
      {
        title: "Dollova — Tore You Too",
        score: 8,
        singleId: "dollova-tore-you-too-single",
      },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "escort",
    artistId: "avya-asti",
    title: "ESCORT",
    cover: "https://i.postimg.cc/1X0snxPn/IMG-20260507-222633-360.jpg",
    releaseDate: "2025-06-20",
    reviewDate: "2025-07-08",
    label: "Independent / АВЯ ASTI",
    text: "Баллада про секс и эскорт, смешанная в очень шлюховатой попсе и невероятно проститутном рэпе",
    tracks: [
      { title: "ЭСКОРТ", score: 8 },
      { title: "ЛОМАЕТ", score: 8 },
      { title: "Я ТВОЯ ДЫРКА", score: 8 },
      { title: "МИЛФА", score: 6 },
      { title: "КОШКА", score: 8 },
      { title: "SEXSTYLE", score: 7 },
      { title: "BDSM", score: 8 },
    ],
    criteria: [
      { title: "Биты", score: 7 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 6 },
    ],
  },
  {
    id: "penis-pussy",
    artistId: "sicka",
    title: "penis pussy",
    cover: "https://i.postimg.cc/KzMgWYrZ/IMG-20260507-223723-016.jpg",
    releaseDate: "2025-06-26",
    reviewDate: "2025-07-08",
    label: "Independent / SiCka",
    text: "История про пизду в туалете, при этом используется семпл из Майнкрафта, а затем ahh-ные и трогательные моменты",
    tracks: [
      { title: "Oh", score: 6 },
      { title: "Sex Vision", score: 7 },
      { title: "And My Pussy-ah", score: 9 },
      { title: "FSP", score: 8 },
      { title: "Shake This Coochie", score: 9 },
      { title: "Toilet", score: 7 },
      { title: "Cunt", score: 6 },
      { title: "Lick and Fap", score: 9 },
      { title: "Burning Classics", score: 5 },
      { title: "Let Me", score: 9, singleId: "sicka-let-me-single" },
      { title: "Initials", score: 10 },
      { title: "A Little Closer", score: 7 },
      { title: "Should I?", score: 5 },
      { title: "Miss Poopie", score: 6 },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "penis-pussy-deluxe",
    artistId: "sicka",
    title: "penis pussy: farty poopy (Deluxe)",
    cover: "https://i.postimg.cc/k4sdqQyY/IMG-20260507-224212-538.jpg",
    releaseDate: "2025-07-13",
    reviewDate: "2025-07-12",
    label: "Independent / SiCka",
    text: "Интрига в начале и самый неожиданный поворот в истории фитов в конце делюкса.",
    tracks: [
      { title: "It Sounds Like", score: 7, number: 15 },
      { title: "Rim", score: 8, number: 16 },
      { title: "Queer Explosion Bomb", score: 7, number: 17 },
      { title: "FSPR (with Slayyyter)", score: 10, number: 18 },
    ],
    criteria: [
      { title: "Original Album", score: 7.8 },
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "ma-life",
    artistId: "pavlova-cookie",
    title: "Ma Life EP",
    cover: "https://i.postimg.cc/Y2JwkCNB/IMG-20260507-224606-965.jpg",
    releaseDate: "2025-06-28",
    reviewDate: "2025-07-21",
    label: "Yandex Market Records",
    text: "Отличная посиделка в каком бы то ни было месте, даже в стриптизе, но было ли хорошим решением выбрать это в середину?",
    tracks: [
      { title: "YMRIML", score: 7 },
      { title: "ДИНАМИТ", score: 8 },
      { title: "СПЕРМА В МОЕЙ ЖОПЕ", score: 5 },
      { title: "ВНЕ ОЧЕРЕДИ", score: 8 },
      { title: "RARARA 2 (Freestyle)", score: 6 },
    ],
    criteria: [
      { title: "Биты", score: 7 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 6 },
    ],
  },
  {
    id: "tits-in-heaven",
    artistId: "sicka",
    title: "TITS IN HEAVEN Mixtape",
    cover: "https://i.postimg.cc/gk8ytgkc/IMG-20260507-230349-727.jpg",
    releaseDate: "2025-07-22",
    reviewDate: "2025-07-22",
    label: "Independent / SiCka",
    text: "На этом микстейпе вы не найдете ниодного ужасного трека, что делает релиз одним из самых крепких в хуендустрии. Определенно, имеет шанс стать самым лучшим релизом SiCka даже после следующих альбомов, если она все таки не уйдет из музыки.",
    tracks: [
      { title: "BUBBLE POOP", score: 8 },
      { title: "I KISSED YOUR BIDET", score: 9 },
      { title: "SEX WITH POOPS", score: 8 },
      { title: "I'M READY", score: 9 },
      { title: "TRACK 5", score: 7, isGrey: false },
      { title: "I'M NOT OKAY", score: 8 },
      { title: "DEEP LIKE PUSSY", score: 8 },
      { title: "HE RULES MY JUICE", score: 7 },
      { title: "VINTAGE PORN", score: 8 },
      { title: "FINAL FART", score: 7 },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "dollodelica",
    artistId: "dollova",
    title: "dollodelica",
    cover: "https://i.postimg.cc/C5Nhzysz/IMG-20260507-230858-435.jpg",
    releaseDate: "2025-07-25",
    reviewDate: "2025-07-26",
    label: "DirtyDollyRecords",
    text: "Очень разнообразный, хоть и дебютный, альбом, который содержит в себе сразу две десятки и одну девятку. Эти оценки — показатель большого качества.",
    tracks: [
      { title: "intro" },
      { title: "2x2", score: 7 },
      { title: "зпшка", score: 7 },
      { title: "queen (bonus track)", score: 8 },
      { title: "пахала (interlude)" },
      { title: "ливай", score: 10 },
      { title: "лям-два (diss)", score: 8 },
      { title: "оплата", score: 10 },
      { title: "jada (feat. Ariana Grande)", score: 10 },
      { title: "уволен", score: 9 },
      { title: "outro" },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "kult-podzalupkinoj",
    artistId: "niksa",
    title: "КУЛЬТ ПОДЗАЛУПКИНОЙ",
    cover: "https://i.postimg.cc/1zcjx9mQ/IMG-20260507-231349-872.jpg",
    releaseDate: "2025-07-26",
    reviewDate: "2025-07-26",
    label: "Independent / NIK$A",
    text: "Может треклист и может показаться маленьким, но он содержит то, что может сделать альбом концептуальным. Почти в каждом треке текст на разные темы — так артистка делится своими разными переживаниями.",
    tracks: [
      { title: "Let's", score: 8 },
      { title: "На пути", score: 7 },
      { title: "В очереди", score: 10 },
      { title: "Overpriced Wig's (interlude)", score: 8 },
      { title: "PuffMeedy", score: 9 },
      { title: "Я плохая", score: 8 },
      { title: "Вне очереди", score: 7 },
      { title: "Без названия (outro)", score: 7 },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "i-am-the-winner",
    artistId: "pavlova-cookie",
    title: "I AM THE WINNER",
    cover: "https://i.postimg.cc/nhHJCwXF/IMG-20260507-232554-471.jpg",
    releaseDate: "2025-08-22",
    reviewDate: "2025-09-09",
    label: "Yandex Market Records",
    text: "Объявление себя королевой в рэпе — субъективное мнение, на которое рэперка имеет полное право, хоть и всё-таки остаются конкуренты.",
    tracks: [
      { title: "ОВЕРСАЙЗ", score: 6 },
      { title: "МУСОРНЫЕ БАЧКИ", score: 7 },
      { title: "ТВОЕЙ КАРЬЕРЕ - П*ЗДА!", score: 8 },
      { title: "TRENDSETTER", score: 6 },
      { title: "BOSS", score: 6 },
      { title: "INTERLUDE" },
      { title: "ГОВНО НА ВЕНТИЛЯТОР", score: 9 },
      { title: "SH1PU4KA!", score: 9 },
      { title: "АНГЕЛЬСКИЙ ГОЛОСОК", score: 8 },
      { title: "ТЫ НЕ ПОБЕДИТЕЛЬ" },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "am-i-the-suchka",
    artistId: "sicka",
    title: "AM I THE SUCHKA?",
    cover: "https://i.postimg.cc/zBDVMH43/IMG-20260508-135900-151.jpg",
    releaseDate: "2025-09-21",
    reviewDate: "2025-11-29",
    label: "Independent / SiCka",
    text: "Уже третий большой релиз от артистки, но она не собирается сдавать в своих позициях и делает ещё один крепкий материал. Назван не коммерцией, но качество немного выше этого звания.",
    tracks: [
      { title: "Baddie Baddie (feat. Ice Spice)", score: 10 },
      { title: "Missis Bitch", score: 8 },
      { title: "BBL", score: 6 },
      { title: "Gowk-Gowk", score: 7 },
      { title: "Please, Can You Fuck Yourself?", score: 7 },
      { title: "Don't Think (feat. Ice Spice)", score: 9 },
      { title: "Дерьмище", score: 10 },
      { title: "Эротический Пупок", score: 8 },
      { title: "Нет, Я Не SiCka", score: 7 },
      { title: "Жральник", score: 9 },
      { title: "Чорная", score: 8 },
      { title: "ЯЛТ, Кирилл", score: 6 },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "am-i-the-suchka-shit-reloaded",
    artistId: "sicka",
    title: "AM I THE SUCHKA?: Shit Reloaded",
    cover: "https://i.postimg.cc/dtfNV89z/IMG-20260508-140543-332.jpg",
    releaseDate: "2025-10-29",
    reviewDate: "2025-11-29",
    label: "Independent / SiCka",
    text: "На дополнении своего второго альбома артистка перегоняет саму себя — она ставит рекорд для всего HueFork по баллам. Наши прогнозы относительно «TITS IN HEAVEN» не сбылись, и она выпустила что-то намного лучше.",
    tracks: [
      { number: 13, title: "Она Пердела На Полу" },
      { number: 14, title: "Дерьмище (Extended & Remastered)", score: 9 },
      { number: 15, title: "#ЯЖирнаяТварь (feat. Baby Cute)", score: 9 },
      { number: 16, title: "Сияние Жопы", score: 9 },
      { number: 17, title: "Пердановна", score: 10 },
      { number: 18, title: "Crow-Horse", score: 8 },
      { number: 19, title: "Ass-Some", score: 10 },
      { number: 20, title: "Hey, Boy (Remastered)", score: 8 },
      { number: 21, title: "Klitor", score: 7 },
      { number: 22, title: "I Just Got Fart In My Hand", score: 6 },
      { number: 23, title: "Дерьмище (Extended)", score: 10 },
      { number: 24, title: "BPLA (Remastered)", score: 8 },
      { number: 25, title: "Hey, Boy", score: 8 },
    ],
    criteria: [
      { title: "Original Album", score: 8.0 },
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "trois",
    artistId: "dollova",
    title: "Trois",
    cover: "https://i.postimg.cc/13whF9J1/IMG-20260508-141150-015.jpg",
    releaseDate: "2025-10-31",
    reviewDate: "2025-11-30",
    label: "DirtyDollyRecords",
    text: "Мы предсказывали победу этого альбома в главной номинации на HUEVKI AWARDS 2026 — и это может полностью оправдаться, ведь этот альбом борется за высший балл! Артистка отказывается от экспериментов и выбирает свой лучший стиль для большого проекта.",
    tracks: [
      { title: "Intro" },
      { title: "Trois", score: 9 },
      { title: "Madam Cum", score: 10 },
      { title: "Diva", score: 9 },
      { title: "Porto Party", score: 8 },
      { title: "Sex Vision", score: 9 },
      { title: "Twerk On The Grave", score: 8 },
      { title: "Dolla Mommy", score: 8 },
      { title: "Bad Bitch (feat. NIK$A)", score: 8 },
      { title: "Outro" },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "trois-deluxe",
    artistId: "dollova",
    title: "Trois Deluxe: Panther Industry",
    cover: "https://i.postimg.cc/3RMZvTSL/IMG-20260508-141204-583.jpg",
    releaseDate: "2025-11-14",
    reviewDate: "2025-11-30",
    label: "DirtyDollyRecords",
    text: "Релиз, названный в честь дисса на оппонентку, в котором каждый трек — крепкий, но кроме этого дисса. Однако сам альбом в качестве теряет не сильно — всего 0.3 балла.",
    tracks: [
      { number: 11, title: "Virus", score: 8 },
      { number: 12, title: "Dolala", score: 7 },
      { number: 13, title: "Dance Shit", score: 10 },
      { number: 14, title: "Bot Hitches", score: 10 },
      { number: 15, title: "Juicy Mobil", score: 8 },
      { number: 16, title: "Are U Ready Skit" },
      { number: 17, title: "Panther Industry Diss", score: 6 },
    ],
    criteria: [
      { title: "Original Album", score: 8.9 },
      { title: "Биты", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "vogue-id",
    artistId: "sicka",
    title: "VOGUE ID EP",
    cover: "https://i.postimg.cc/X7TX3Yp1/IMG-20260508-141934-156.jpg",
    releaseDate: "2025-11-16",
    reviewDate: "2025-11-30",
    label: "Farting Lesbians",
    text: "Самый маленький релиз артистки из нескольких треков (не считая «HIT NIK$A UP»), но все ещё хорошего качества секса. Не для всех.",
    tracks: [
      { title: "AssQueen", score: 8 },
      { title: "Smack It Up", score: 9 },
      { title: "PussyCode", score: 10 },
      { title: "Sexy Toilet", score: 8 },
      { title: "Eat This Pussy", score: 7 },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "tits-in-hell",
    artistId: "sicka",
    title: "TITS IN HELL Mixtape",
    cover: "https://i.postimg.cc/MTVJ7zWn/IMG-20260508-142142-723.jpg",
    releaseDate: "2025-12-01",
    reviewDate: "2025-12-01",
    label: "Farting Lesbians",
    text: "«Плачь сука плачь плачь» — только это микстейп. В целом, хороший сестринский проект прошлого микстейпа «TITS IN HEAVEN», полностью отличается от ее прошлого творчества, и даже от первого микстейпа.",
    tracks: [
      { title: "PRICKLY ANUS", score: 7 },
      { title: "YUMMY MOMMY", score: 7 },
      { title: "LOT OF CUM", score: 6 },
      { title: "PORNING", score: 10 },
      { title: "JUMPIN' LIKE BUNNY", score: 8 },
      { title: "FARTA POOPA", score: 9 },
      { title: "JELLY BUMP", score: 7 },
      { title: "DICK KNOWS ME BEST", score: 8 },
      { title: "SUCK TOMORROW", score: 9 },
      { title: "FINAL ASS" },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "pertty-and-petty",
    artistId: "avya-asti",
    title: "Pertty&Petty EP",
    cover: "https://i.postimg.cc/Kz23rvPb/IMG-20260508-144517-057.jpg",
    releaseDate: "2026-01-23",
    reviewDate: "2026-02-21",
    label: "Independent / АВЯ ASTI",
    text: "Если вы просто хотите потрясти своим телом, а особенно пятой точкой — этот мини-альбом для вас. Не слишком большой хронометраж, но удовольствие доставляет так, что Господи помилуй.",
    tracks: [
      { title: "YUP", score: 8 },
      { title: "I'M", score: 7 },
      { title: "HERMES", score: 7 },
      { title: "BAP! BAP!", score: 8 },
      { title: "STRAP ON", score: 9 },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "y3k",
    artistId: "sicka",
    title: "Y3K!",
    cover: "https://i.postimg.cc/6Qyxjdhq/IMG-20260207-233206-653.jpg",
    releaseDate: "2026-02-15",
    reviewDate: "2026-05-08",
    label: "Farting Lesbians",
    text: "Рэперка переходит в свою эру будущего, где показывает свое настоящее качество музыки. Чего стоят только губы на пол лица на обложке альбома — она их использует как музыкальный инструмент для своих треков. Она не боится делать много треков, потому что это её боятся.",
    tracks: [
      { title: "Twerking Core", score: 10 },
      { title: "福克米 内嘎", score: 8 },
      { title: "Such Hoes", score: 9 },
      { title: "Coming Out", score: 9 },
      { title: "Don't Care", score: 7 },
      { title: "TMBody", score: 9 },
      { title: "American Stick", score: 8 },
      { title: "Mess", score: 9 },
      { title: "JeSOS", score: 9 },
      { title: "Vagina Giant", score: 9 },
      { title: "No Free Promo", score: 9 },
      { title: "Go! SiCka! Go!", score: 10 },
      { title: "Tranny", score: 8 },
      { title: "Pretty Privilege", score: 8 },
      { title: "Everything Fucks Me", score: 7 },
      { title: "EFM" },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "escort-2",
    artistId: "avya-asti",
    title: "ESCORT 2",
    cover: "https://i.postimg.cc/YC8b4ZYY/IMG-20260508-151118-057.jpg",
    releaseDate: "2026-03-21",
    reviewDate: "2026-05-08",
    label: "OOO LABLE MALIK DELGATY AND AVEE ASTI",
    text: "На своем сестринском проекте дебютного альбома артистка показывает новое качество, которого в ее дискографии еще не было. Тут и рэп, и рок, и поп, но даже так все звучит, как цельная композиция — это явный показатель того, что она явно умеет звучать хорошо везде.",
    tracks: [
      { title: "INTRO", score: 8 },
      { title: "ZABIRAYU", score: 7 },
      { title: "BABY", score: 10 },
      { title: "V TVOEY GOLOVE", score: 7 },
      { title: "FUCK, DAMN", score: 7 },
      { title: "PRIG SCOCK", score: 9 },
      { title: "LA FRANCE", score: 10 },
      { title: "XALAVCHIK", score: 8 },
      { title: "SHITBARS2", score: 9 },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "pregnant-with-bitch",
    artistId: "sicka",
    title: "Pregnant With Bitch Mixtape",
    cover:
      "https://i.postimg.cc/9QXsNGBb/file-00000000e770720a97fcb5b159765252.png",
    releaseDate: "2026-04-26",
    reviewDate: "2026-05-08",
    label: "Farting Lesbians",
    text: "Если все прошлые микстейпы были нацелены на узкую аудиторию, которая абсолютно не относится к хуендустрии, поэтому они вышли delulu, то на этом микстейпе все случилось наоборот, более того, это первый микстейп в дискографии артистки, который не относится к арке «TITS IN». Сичка немного пробует себя в новых экспериментальных жанрах, например, «Anus», который невозможно слушать без мефедрона или чего-то типо того. Тем не менее, релиз получает одну из самых высоких оценок в сервисе.",
    tracks: [
      { title: "Pregnant With Bitch", score: 9 },
      { title: "Brainless", score: 9 },
      { title: "Posay Cum", score: 6 },
      { title: "What The Hell", score: 10 },
      { title: "Anus" },
      { title: "TeaTea", score: 10 },
      { title: "Shut That Hole Up", score: 10 },
      { title: "Actually, No", score: 8 },
      { title: "ST Remoaned", score: 7 },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "cum-mania",
    artistId: "dollova",
    title: "CUM MANIA",
    cover: "https://i.postimg.cc/FKxyCBhy/IMG-20260508-160333-769.jpg",
    releaseDate: "2026-05-22",
    reviewDate: "2026-05-22T12:00:00Z",
    label: "DirtyDollyRecords",
    text: "Третий альбом хуендустристской артистки наполнен разнообразными битами и известными семплами на них. Каждый трек звучит как что-то другое и практически не похожее на прошлое, от такого даже мозг начинает кипеть, как сперма от раскаленного шарика. Каждые 2 минуты — это какая-то другая вселенная, которая либо сведёт вас с ума, либо заставит вас захотеть вернуться обратно.",
    tracks: [
      { title: "DOLLY & GABBANA", score: 10 },
      { title: "I WANT A BIG BIG (feat. Ksivat)", score: 10 },
      { title: "MADAM CUM 2", score: 9 },
      { title: "CUM MANIA", score: 10 },
      { title: "ASS+CUM", score: 9 },
      { title: "BOMBITA", score: 8 },
      { title: "D RAP", score: 5 },
      { title: "Э!", score: 9 },
      { title: "BB", score: 9 },
      { title: "AMG ASS", score: 8 },
      { title: "PATRONA (feat. ROMBOLLA)", score: 8 },
      { title: "MELON 18+", score: 10 },
      { title: "DOLLY MOMENT", score: 8 },
    ],
    criteria: [
      { title: "Биты", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "ya-ebala-vashi-rti-sukkha",
    artistId: "pavlova-cookie",
    title: "ya ebala vashi rti sukkha EP",
    cover: "https://i.postimg.cc/FRHjfRpB/IMG-20260508-213011-967.jpg",
    releaseDate: "2026-05-09",
    reviewDate: "2026-05-09",
    label: "YMR & Farting Lesbians",
    text: "С невышедшим вторым альбомом «BEEZ TAKING OVER» артистки случились разногласия между рэперкой, релизом и лейблом. В итоге, все они пришли к выводу, что выйдет EP с треками, которые должны были войти в альбом. Было ли это зря или нет — сложный вопрос, но качество этого мини-альбома выше всех релизов Павловы.",
    tracks: [
      { title: "million dollar babe", score: 9 },
      { title: "selfie", score: 7 },
      { title: "skinny jeanz", score: 9 },
    ],
    criteria: [
      { title: "Биты", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 3 },
    ],
  },
  {
    id: "ariana-grande-petal",
    artistId: "ariana-grande",
    title: "petal",
    cover: "https://images.genius.com/2146b311efb5d1f05a87343d95edea03.1000x1000x1.png",
    releaseDate: "2026-07-31",
    label: "Babydoll Music",
    text: "Неизвестно",
    isUpcoming: true,
    tracks: [
      { title: "track 1" },
      { title: "hate that i made you love me", score: 10 },
      { title: "track 3" },
      { title: "track 4" },
      { title: "track 5" },
      { title: "track 6" },
      { title: "track 7" },
      { title: "track 8" },
      { title: "track 9" },
      { title: "track 10" },
      { title: "track 11" },
      { title: "track 12" }
    ],
    criteria: [
      { title: "Биты" },
      { title: "Флоу" },
      { title: "Потенциал хита" },
      { title: "Визуал" }
    ]
  },
  {
    id: "ariana-grande-eternal-sunshine",
    artistId: "ariana-grande",
    title: "eternal sunshine",
    cover: "https://i.postimg.cc/dtkrfv1p/IMG-20260516-153502-888.jpg",
    releaseDate: "2024-03-08",
    reviewDate: "2026-05-16T11:00:00Z",
    label: "Republic Records",
    text: "Этот альбом — это очень личная и атмосферная поп-запись, где нежный R&B и хаус-звучание сочетаются с темами расставания, памяти и взросления. Проект ощущается более зрелым и цельным, чем многие прошлые релизы Арианы, а треки вроде “we can’t be friends” и “imperfect for you” особенно хорошо раскрывают его эмоциональную сторону.",
    tracks: [
      { title: "intro (end of the world)", score: 9 },
      { title: "bye", score: 9 },
      { title: "don't wanna break up again", score: 10 },
      { title: "Saturn Returns interlude" },
      { title: "eternal sunshine", score: 9 },
      { title: "supernatural", score: 9 },
      { title: "true story", score: 10 },
      { title: "the boy is mine", score: 10 },
      { title: "yes, and?", score: 10 },
      { title: "we can't be friends (wait for your love)", score: 10 },
      { title: "i wish i hated you", score: 8 },
      { title: "imperfect for you", score: 8 },
      { title: "ordinary things (feat. Nonna)", score: 9 },
    ],
    criteria: [
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 },
    ],
    noTop: true,
    noAwards: true,
  },
  {
    id: "ariana-grande-eternal-sunshine-deluxe",
    artistId: "ariana-grande",
    title: "eternal sunshine: brighter days ahead",
    cover: "https://i.postimg.cc/nLRq5LvP/IMG-20260516-153508-090.jpg",
    releaseDate: "2025-03-28",
    reviewDate: "2026-05-16T12:00:00Z",
    label: "Republic Records",
    text: "eternal sunshine deluxe: brighter days ahead — это более кинематографичное и эмоционально завершённое переиздание альбома, где Ariana Grande сильнее уходит в тему воспоминаний, потерь и принятия себя. Новые треки звучат мягче и атмосфернее, а весь проект вместе с короткометражкой ощущается как красивое завершение эры eternal sunshine.",
    tracks: [
      { title: "intro (end of the world) [extended]", score: 10 },
      { title: "twilight zone", score: 9 },
      { title: "warm", score: 8 },
      { title: "dandelion", score: 10 },
      { title: "past life", score: 10 },
      { title: "Hampstead", score: 8 },
    ],
    criteria: [
      { title: "Original Album", score: 9.3 },
      { title: "Биты", score: 9 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 },
    ],
    noTop: true,
    noAwards: true,
  },
  {
    id: "dollova-msp-single",
    artistId: "dollova",
    title: "msp",
    cover: "https://i.postimg.cc/6QGP6FYj/IMG-20260516-133818-225.jpg",
    releaseDate: "2025-08-31",
    reviewDate: "2026-05-16T11:30:00Z",
    label: "DirtyDollyRecords",
    text: "Артистка продолжает радовать нас новыми треками в конце этого лета, поэтому на последок решила выпустить последний хит, который завершает ее первую эру. Композиция представляет собой танцевальный трек, который так и просит, чтобы ты этим summer поднял свою pussy и потряс ею.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "dollova-dolly-gabbana-single",
    artistId: "dollova",
    title: "DOLLY & GABBANA",
    cover: "https://i.postimg.cc/7h1HN3WZ/IMG-20260515-140758-839.jpg",
    releaseDate: "2026-04-17",
    reviewDate: "2026-05-16",
    label: "DirtyDollyRecords",
    text: "Лид-сингл к грядущему альбому артистки уже показывает качество, к которому стоит готовиться на пластинке. Рэперка уходит только от поп-хитов с прямой бочкой и приходит к чему-то новому, что звучит.... Звучит.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "ksivat-shake-single",
    artistId: "ksivat",
    title: "Shake",
    cover: "https://i.postimg.cc/KvzM9CQJ/IMG-20260515-221131-455.jpg",
    releaseDate: "2026-05-15",
    reviewDate: "2026-05-16",
    label: "DPM Records",
    text: "Динамичный и заедающий трек, который отлично справляется со своей главной задачей — заставить слушателя двигаться. Качественный продакшн и уверенная подача делают этот трек сильным представителем своего жанра.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 7 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "ksivat-bez-obid-single",
    artistId: "ksivat",
    title: "Без Обид",
    cover: "https://i.postimg.cc/KvzM9CQJ/IMG-20260515-221131-455.jpg",
    releaseDate: "2026-05-15",
    reviewDate: "2026-05-16",
    label: "DPM Records",
    text: "Крепкая представительница жанра, которая не изобретает велосипед, но очень грамотно работает с проверенными формулами. Трек обладает отличным вайбом для ночных поездок или фонового прослушивания в заведении, выделяясь приятным тембром артистки.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "ksivat-lauma-supremacy-single",
    artistId: "ksivat",
    title: "Lauma Supremacy",
    cover: "https://i.postimg.cc/wBhyyzTY/IMG-20260515-222258-515.jpg",
    releaseDate: "2026-05-01",
    reviewDate: "2026-05-16",
    label: "DPM Records",
    text: "Вновь трек о любимой игре и любимом персонаже из этой игры от артистки. Создаётся ощущение, что кроме этой рутины, у нее нет жизни.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 9 },
      { title: "Бит", score: 7 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "avya-asti-pay-me-baby-single",
    artistId: "avya-asti",
    title: "PAY ME, BABY",
    cover: "https://i.postimg.cc/2yrm3p9c/IMG-20260515-225529-525.jpg",
    releaseDate: "2026-04-29",
    reviewDate: "2026-05-16",
    label: "OOO LABLE MALIK DELGATY AND AVEE ASTI",
    text: "Очень стильный и коммерчески выверенный трек, который буквально излучает вайб дорогой жизни. Идеальный баланс между поп-звучанием и рэп-подачей, создающий образ недосягаемой и успешной артистки.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "avya-asti-fuck-damn-single",
    artistId: "avya-asti",
    title: "FUCK, DAMN",
    cover: "https://i.postimg.cc/L6yR4btX/IMG-20260515-225955-036.jpg",
    releaseDate: "2026-03-01",
    reviewDate: "2026-05-16",
    label: "OOO LABLE MALIK DELGATY AND AVEE ASTI",
    text: "Бэнгер для клубов, построенный на резких фразах и мощном ритме. Эффективно справляется со своей главной задачей: создавать дерзкое настроение и заставлять двигаться.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 7 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "avya-asti-shitbars-single",
    artistId: "avya-asti",
    title: "SHITBARS",
    cover: "https://i.postimg.cc/HkRgX8PC/IMG-20260515-230610-929.jpg",
    releaseDate: "2025-12-19",
    reviewDate: "2026-05-16",
    label: "АВЯ ASTI",
    text: "Трек оправдывает своё название, делая ставку на поток сознания и свободную форму без строгого припева. Это крепкая демонстрация харизмы и способности артистки удерживать внимание слушателя исключительно за счёт подачи и дерзкого текста.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 6 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "pavlova-cookie-cocaine-ecstasy-dope-crack-single",
    artistId: "pavlova-cookie",
    title: "COCAINE, ECSTASY, DOPE, CRACK",
    cover: "https://i.postimg.cc/Bb6w8CDH/IMG-20260515-231256-516.jpg",
    releaseDate: "2026-04-17",
    reviewDate: "2026-05-16",
    label: "YMR & Farting Lesbians",
    text: "Спустя долгий перерыв, выходит коротенький трек о зависимостях артистки. Эксперимент в жанре для неё, который, хоть и имеет одну из низких оценок для HueFork, более менее удался.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 7 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 5 },
    ],
  },
  {
    id: "pavlova-cookie-reflex-single",
    artistId: "pavlova-cookie",
    title: "REFLEX",
    cover: "https://i.postimg.cc/ncNwzBLj/IMG-20260515-232942-187.jpg",
    releaseDate: "2025-12-12",
    reviewDate: "2026-05-16",
    label: "YMR & Farting Lesbians",
    text: "Ламповый, хороший трек, который своим припевом может засидеть в голове надолго. Является лид-синглом к альбому артистки, и уже сейчас можем высчитать примерное качество.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 6 },
    ],
  },
  {
    id: "pavlova-cookie-shimmy-shimmy-ya-single",
    artistId: "pavlova-cookie",
    title: "SHIMMY SHIMMY YA! (feat. МЭЙБИ БЭЙБИ)",
    cover: "https://i.postimg.cc/dtZ4z3jg/IMG-20260515-233023-732.jpg",
    releaseDate: "2025-11-07",
    reviewDate: "2026-05-16",
    label: "YMR & Farting Lesbians",
    text: "Коллаборация артисток, которых мы уже ранее слышали вместе. Вместе они не собираются сдавать позиции и продолжают давать качественный материал.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 7 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "sicka-alarm-freestyle-single",
    artistId: "sicka",
    title: "Alarm Freestyle",
    cover: "https://i.postimg.cc/R0pgkHyk/IMG-20260515-233343-895.jpg",
    releaseDate: "2026-04-15",
    reviewDate: "2026-05-16",
    label: "Farting Lesbians",
    text: "Рэперка не изменяет своей традиции и выпускает новый фристайл на этот месяц, который отличается выбранным стилем. В семпле бита наблюдается кошмар каждого человека, у которого когда-либо был Samsung, а артистка своим голосом добавляет этому потенциал.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 7 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 6 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "sicka-twerking-core-extended-single",
    artistId: "sicka",
    title: "Twerking Core (Extended)",
    cover: "https://i.postimg.cc/VkfQ1XZN/IMG-20260515-234124-169.jpg",
    releaseDate: "2026-03-29",
    reviewDate: "2026-05-16",
    label: "Farting Lesbians",
    text: "В продолжение эры «Y3K!», и при этом в её же завершение, артистка продлевает интро своего альбома на одну с половиной минуты. Куплет добавляет больше драйва и игривости к изначальному треку, а также новое аутро. И при этом, звучит ничем ни хуже, чем первая версия.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "sicka-pizda-freestyle-single",
    artistId: "sicka",
    title: "Pizda Freestyle",
    cover: "https://i.postimg.cc/8Ck6hXyX/IMG-20260515-234629-167.jpg",
    releaseDate: "2026-03-06",
    reviewDate: "2026-05-16",
    label: "Farting Lesbians",
    text: "Для данного фристайла артистка выбрала семплом жару от губастой прошмандовки. И кто, если не она, исправит ситуацию на этом бите?",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "dollova-e-single",
    artistId: "dollova",
    title: "Э!",
    cover: "https://i.postimg.cc/fbwMy6Hk/IMG-20260516-000657-568.jpg",
    releaseDate: "2026-02-27",
    reviewDate: "2026-05-16",
    label: "DirtyDollyRecords",
    text: "Взрывной трек, под который можно двигаться одновременно и быстро, и медленно. Ритмичный бит и повторяющийся припев делают его вирусным и запоминающимся.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "dollova-sicka-booty-drop-single",
    artistId: "dollova",
    artistIds: ["dollova", "sicka"],
    title: "Booty Drop (feat. SiCka)",
    cover: "https://i.postimg.cc/PfBpJ51C/IMG-20260516-000632-835.jpg",
    releaseDate: "2026-01-16",
    reviewDate: "2026-05-16",
    label: "DirtyDollyRecords",
    text: "На данный момент, самый сильный фит в хуендустрии, под который реально можно устроить не только booty, но и vogue drop. Трек идеально справляется со своей главной задачей тряски тела, в остальном большого смысла он не несёт.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "niksa-sorry-girls-single",
    artistId: "niksa",
    title: "SORRY, GIRLS",
    cover: "https://i.postimg.cc/rFskB1DY/IMG-20260516-001600-788.jpg",
    releaseDate: "2025-07-21",
    reviewDate: "2026-05-16",
    label: "Yandex Market Records",
    text: "Никса устала. Пов ты Марьяна Ро. Посмотрим, простят ли ее Dollova, SiCka и Pavlova Cookie.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 7 },
      { title: "Припев", score: 7 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 7 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 6 },
    ],
  },
  {
    id: "niksa-ne-sopernitsy-single",
    artistId: "niksa",
    title: "НЕ СОПЕРНИЦЫ",
    cover: "https://i.postimg.cc/Jnxfg0mv/IMG-20260516-001628-582.jpg",
    releaseDate: "2025-07-21",
    reviewDate: "2026-05-16",
    label: "Yandex Market Records",
    text: "Никса не хочет бифиться, потому что ей никто не соперник. Своих оппонентов она представляет в виде дилдо.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 8 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 7 },
      { title: "Визуал", score: 7 },
    ],
  },
  {
    id: "niksa-rap-bullying-single",
    artistId: "niksa",
    title: "РЭП БУЛЛИНГ",
    cover: "https://i.postimg.cc/g0P1280b/IMG-20260516-001652-652.jpg",
    releaseDate: "2025-07-20",
    reviewDate: "2026-05-16",
    label: "Yandex Market Records",
    text: "Никса реагирует на диссы.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 7 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 7 },
      { title: "Бит", score: 7 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 6 },
      { title: "Визуал", score: 6 },
    ],
  },
  {
    id: "ksivat-lauma-single",
    artistId: "ksivat",
    title: "Lauma",
    cover: "https://i.postimg.cc/BQwpr0J1/IMG-20260517-194443-450.jpg",
    releaseDate: "2025-09-19",
    reviewDate: "2026-05-17T23:00:00Z",
    label: "Independent / Ksivat",
    text: "Снова новый трек, и снова про игру Genshin Impact. Здесь артистка описывает свои отношения с персонажем Нилу, на которую она успела слить большое количество круток, а оказалось что она для Ksivat будет бесполезной.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 10 },
    ],
  },
  {
    id: "dollova-fat-guest-single",
    artistId: "dollova",
    title: "fat guest",
    cover: "https://i.postimg.cc/Gh3kKhTQ/IMG-20260517-203243-983.jpg",
    releaseDate: "2025-08-31",
    reviewDate: "2026-05-17T23:30:00Z",
    label: "DirtyDollyRecords",
    text: "Артистка представляет новый танцевальный поп-трек, который должен был войти в её дебютный альбом «dollodelica». В этом треке она вспоминает времена на работе, когда к ней пришёл настолько жирный посетитель, что он сломал стул и стол, за которые он сел. И полресторана.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 10 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 8 },
    ],
  },
  {
    id: "sicka-lick-and-fap-single",
    artistId: "sicka",
    title: "Lick and Fap",
    cover: "https://i.postimg.cc/fb56pbTB/IMG-20260517-211009-340.jpg",
    releaseDate: "2025-06-21",
    reviewDate: "2026-05-17T23:59:58Z",
    label: "Independent / SiCka",
    text: "Артистка готовит свою аудиторию к выходу нового альбома. Трек уже до релиза завоевал сердца фанатов своими сниппетами, и не только фанатов. Это первая композиция исполнительницы в танцевальном стиле. Здесь она восхваляет свою личность и пятку.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 10 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 8 },
      { title: "Потенциал хита", score: 10 },
      { title: "Визуал", score: 6 },
    ],
  },
  {
    id: "ksivat-matcha-single",
    artistId: "ksivat",
    title: "Matcha",
    cover: "https://i.postimg.cc/Wb4sFjRb/IMG-20260518-120006-829.jpg",
    releaseDate: "2026-02-20",
    reviewDate: "2026-05-18T12:01:00Z",
    label: "DPM Records",
    text: "Кофейно-зеленый вайбик в перемешку с сумасшедшим битом, который сбивает с толку. Не минус, а наоборот добавляет тряски телу.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 9 },
    ],
  },
  {
    id: "sicka-let-me-single",
    artistId: "sicka",
    title: "Let Me from Huevision 2025",
    cover: "https://i.postimg.cc/brkbcBDW/IMG-20260428-110522-876.jpg",
    releaseDate: "2025-06-08",
    reviewDate: "2026-05-18T12:05:00Z",
    label: "HUEVKI",
    text: "Заигрывающий трек, в котором представительница Ревостана предлагает кокетливо «пернуть и насрать на лицо». Представляет свою страну во всей красе.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 8 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
    ],
  },
  {
    id: "niksa-business-single",
    artistId: "niksa",
    title: "Business from Huevision 2025",
    cover: "https://i.postimg.cc/brkbcBDW/IMG-20260428-110522-876.jpg",
    releaseDate: "2025-06-08",
    reviewDate: "2026-05-18T12:04:00Z",
    label: "HUEVKI",
    text: "Выигрыш России в 2025 году на Хуевидении благодаря Никсе и этому треку. Дерзко, стервозно, нежночастно.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 10 },
      { title: "Припев", score: 9 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 },
      { title: "Нежная часть" },
    ],
  },
  {
    id: "ksivat-5-minutes-single",
    artistId: "ksivat",
    title: "5 Minutes from Huevision 2025",
    cover: "https://i.postimg.cc/brkbcBDW/IMG-20260428-110522-876.jpg",
    releaseDate: "2025-06-08",
    reviewDate: "2026-05-18T12:03:00Z",
    label: "HUEVKI",
    text: "Настоящий победитель по нашему скромному мнению, если учитывать только трек. На данном произведении можем запечатлеть момент, когда артистка ещё не была окончательно «огеншинирована» в своих песнях.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 10 },
    ],
  },
  {
    id: "dollova-tore-you-too-single",
    artistId: "dollova",
    title: "Tore You Too from Huevision 2025",
    cover: "https://i.postimg.cc/brkbcBDW/IMG-20260428-110522-876.jpg",
    releaseDate: "2025-06-08",
    reviewDate: "2026-05-18T12:02:00Z",
    label: "HUEVKI",
    text: "Не попадающий в бит флоу в первом куплете рушит мнение о треке с самого начала. Самый вокальный трек на первом главном песенном конкурсе, но немного под влиянием флопа.",
    isSingle: true,
    singleCriteria: [
      { title: "Куплеты", score: 6 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 9 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 7 },
      { title: "Потенциал хита", score: 9 },
    ],
  },
  {
    id: "sicka-fu-ke-mi-nei-ga",
    artistId: "sicka",
    isSingle: true,
    isUpcoming: false,
    title: "福克米 内嘎",
    cover: "https://i.postimg.cc/fTt3XKqh/IMG-20260529-175536-947.jpg",
    releaseDate: "2025-12-20",
    reviewDate: "2026-05-29",
    label: "Independent / SiCka",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 8 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 9 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 9 },
      { title: "Визуал", score: 9 }
    ],
    text: "Один из самых просящих на секс треков рэперки, а на этот раз она прямо обращается к человеку, который должен ее трахнуть — ниха."
  },
  {
    id: "sicka-divas-born-intro",
    artistId: "sicka",
    isSingle: true,
    isUpcoming: false,
    albumId: "sicka-united-states-of-sicka",
    title: "Diva's Born (Intro)",
    cover: "https://i.postimg.cc/yddB6XY8/file-0000000083a47246a1087a141da0ebe2.png",
    releaseDate: "2026-05-31",
    reviewDate: "2026-05-31",
    label: "Farting Lesbians",
    singleCriteria: [
      { title: "Куплеты", score: 9 },
      { title: "Припев", score: 10 },
      { title: "Дополнительно", score: 8 },
      { title: "Бит", score: 10 },
      { title: "Флоу", score: 9 },
      { title: "Потенциал хита", score: 8 },
      { title: "Визуал", score: 10 }
    ],
    text: "Экспериментальный звук для рэперки, который открывает ее эру Соединённых Штатов уже не постами в канале, а в треках. В этой композиции артистка совмещает вместе быструю рэп-читку в куплетах и магический вокал в припеве. Этот трек заявляет о высоком статусе и амбициях Сики."
  },
];

export const getArtist = (id) => artists.find((a) => a.id === id);
export const getReview = (id) => reviews.find((r) => r.id === id);
export const getReviewsForArtist = (artistId) =>
  reviews.filter(
    (r) =>
      r.artistId === artistId ||
      (r.artistIds && r.artistIds.includes(artistId)),
  );
export const getScore = (review) => {
  if (review.isUpcoming) return 0;

  if (review.isSingle && review.singleCriteria) {
    const scoredCriteria = review.singleCriteria.filter(
      (c) => typeof c.score === "number",
    );
    if (scoredCriteria.length === 0) return 0;
    const sum = scoredCriteria.reduce((acc, c) => acc + c.score, 0);
    return Number((sum / scoredCriteria.length).toFixed(1));
  }

  const scoredTracks =
    review.tracks?.filter((t) => typeof t.score === "number") || [];
  const tracksMean =
    scoredTracks.length > 0
      ? scoredTracks.reduce((acc, t) => acc + t.score, 0) / scoredTracks.length
      : 0;

  const scoredCriteria =
    review.criteria?.filter((c) => typeof c.score === "number") || [];
  const critMean =
    scoredCriteria.length > 0
      ? scoredCriteria.reduce((acc, c) => acc + c.score, 0) /
        scoredCriteria.length
      : 0;

  if (scoredTracks.length > 0 && scoredCriteria.length > 0) {
    return Number(((tracksMean + critMean) / 2).toFixed(1));
  }
  if (scoredTracks.length > 0) return Number(tracksMean.toFixed(1));
  if (scoredCriteria.length > 0) return Number(critMean.toFixed(1));

  if (review.score !== undefined) return review.score;
  return 0;
};

export const getGlobalRank = (reviewId, isSingle) => {
  const sorted = [...reviews]
    .filter((r) => {
      if (r.isUpcoming) return false;
      if (!!r.isSingle !== !!isSingle) return false;
      if (r.noTop) return false;
      const artist = artists.find((a) => a.id === r.artistId);
      if (artist && artist.isGlobal) return false;
      return true;
    })
    .sort((a, b) => getScore(b) - getScore(a));
  const idx = sorted.findIndex((r) => r.id === reviewId);
  return idx >= 0 ? idx + 1 : 0;
};

export const getArtistValue = (artistId, customReviews = reviews) => {
  const artistReviews = customReviews.filter(
    (r) =>
      (r.artistId === artistId ||
        (r.artistIds && r.artistIds.includes(artistId))) &&
      !r.isUpcoming &&
      !r.noTop,
  );
  if (artistReviews.length === 0) return 0;

  let totalScore = 0;
  let totalWeight = 0;

  artistReviews.forEach((r) => {
    const w = r.isSingle ? 1 : 5;
    totalScore += getScore(r) * w;
    totalWeight += w;
  });

  const BASELINE_SCORE = 7.5;
  const BASELINE_WEIGHT = 3;

  const bayesianAvg =
    (totalScore + BASELINE_SCORE * BASELINE_WEIGHT) /
    (totalWeight + BASELINE_WEIGHT);

  const rawAvg = totalScore / totalWeight;
  let volumeBonus = 0;
  if (rawAvg > 7.0) {
    const qualityFactor = (Math.min(rawAvg, 10.0) - 7.0) / 3.0;
    const maxBonusForVolume = totalWeight * 0.04;
    volumeBonus = maxBonusForVolume * qualityFactor;
  }

  return Math.min(bayesianAvg + volumeBonus, 10.0);
};

export const getArtistRank = (reviewId, artistId, isSingle) => {
  const artistReviews = getReviewsForArtist(artistId).filter(
    (r) => !r.isUpcoming && !!r.isSingle === !!isSingle,
  );
  const sorted = [...artistReviews].sort((a, b) => getScore(b) - getScore(a));
  const idx = sorted.findIndex((r) => r.id === reviewId);
  return idx >= 0 ? idx + 1 : 0;
};

export const formatDate = (dateStr) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString("ru-RU", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

export const formatYear = (dateStr) => {
  const date = new Date(dateStr);
  return date.getFullYear().toString();
};
